export interface ClaimLineInput {
  cptCode: string
  icd10Codes: string[]
  modifier?: string
  units: number
  chargeAmount: number
  description?: string
}

export interface SubmitClaimInput {
  practiceId: string
  providerId: string
  patientId: string
  serviceDate: string
  lineItems: ClaimLineInput[]
}

export interface ClaimSummary {
  id: string
  patientName: string
  providerName: string
  serviceDate: string
  totalCharge: number
  claimStatus: string
  submittedAt: string | null
  denialReason: string | null
  paidAmount: number | null
}

// Common CPT codes across all 25 outpatient specialties on Claima.
// The `specialty` field enables UI filtering by specialty in claim entry forms.
export const COMMON_CPT_CODES = [
  // E&M — office visits (all specialties)
  { code: "99202", description: "New patient, straightforward MDM",           specialty: "general" },
  { code: "99203", description: "New patient, low MDM",                        specialty: "general" },
  { code: "99204", description: "New patient, moderate MDM",                   specialty: "general" },
  { code: "99205", description: "New patient, high MDM",                       specialty: "general" },
  { code: "99211", description: "Established patient, minimal",                specialty: "general" },
  { code: "99212", description: "Established patient, straightforward MDM",    specialty: "general" },
  { code: "99213", description: "Established patient, low MDM",                specialty: "general" },
  { code: "99214", description: "Established patient, moderate MDM",           specialty: "general" },
  { code: "99215", description: "Established patient, high MDM",               specialty: "general" },
  // Preventive medicine — adults
  { code: "99385", description: "Preventive visit, new patient, 18–39 yr",     specialty: "general" },
  { code: "99386", description: "Preventive visit, new patient, 40–64 yr",     specialty: "general" },
  { code: "99387", description: "Preventive visit, new patient, 65+ yr",       specialty: "general" },
  { code: "99395", description: "Preventive visit, established patient, 18–39 yr", specialty: "general" },
  { code: "99396", description: "Preventive visit, established patient, 40–64 yr", specialty: "general" },
  { code: "99397", description: "Preventive visit, established patient, 65+ yr",   specialty: "general" },
  { code: "G0402", description: "Welcome to Medicare exam (IPPE)",             specialty: "general" },
  { code: "G0438", description: "Annual Wellness Visit, initial (Medicare)",   specialty: "general" },
  { code: "G0439", description: "Annual Wellness Visit, subsequent (Medicare)", specialty: "general" },
  // Preventive medicine — pediatric
  { code: "99381", description: "Preventive visit, new patient, infant (<1 yr)",   specialty: "pediatrics" },
  { code: "99382", description: "Preventive visit, new patient, 1–4 yr",           specialty: "pediatrics" },
  { code: "99383", description: "Preventive visit, new patient, 5–11 yr",          specialty: "pediatrics" },
  { code: "99384", description: "Preventive visit, new patient, 12–17 yr",         specialty: "pediatrics" },
  { code: "99391", description: "Preventive visit, established patient, infant",    specialty: "pediatrics" },
  { code: "99392", description: "Preventive visit, established patient, 1–4 yr",   specialty: "pediatrics" },
  { code: "99393", description: "Preventive visit, established patient, 5–11 yr",  specialty: "pediatrics" },
  { code: "99394", description: "Preventive visit, established patient, 12–17 yr", specialty: "pediatrics" },
  // Family Medicine / Internal Medicine
  { code: "93000", description: "ECG, 12-lead with interpretation",            specialty: "general" },
  { code: "85025", description: "CBC with differential",                        specialty: "general" },
  { code: "80053", description: "Comprehensive metabolic panel",                specialty: "general" },
  { code: "80061", description: "Lipid panel",                                  specialty: "general" },
  { code: "83036", description: "HbA1c",                                        specialty: "general" },
  { code: "81003", description: "Urinalysis, automated",                        specialty: "general" },
  { code: "36415", description: "Routine venipuncture",                         specialty: "general" },
  { code: "90471", description: "Immunization administration, first injection", specialty: "general" },
  { code: "90472", description: "Immunization administration, each add'l injection", specialty: "general" },
  { code: "99406", description: "Smoking cessation counseling, 3–10 min",      specialty: "general" },
  { code: "99407", description: "Smoking cessation counseling, >10 min",       specialty: "general" },
  { code: "20552", description: "Injection, trigger point, 1–2 muscles",       specialty: "general" },
  { code: "20553", description: "Injection, trigger point, 3+ muscles",        specialty: "general" },
  // Pediatrics
  { code: "99460", description: "Initial newborn evaluation",                   specialty: "pediatrics" },
  { code: "99461", description: "Normal newborn, subsequent hospital visit",    specialty: "pediatrics" },
  { code: "96110", description: "Developmental screening",                      specialty: "pediatrics" },
  { code: "96127", description: "Brief emotional/behavioral assessment",        specialty: "pediatrics" },
  { code: "99173", description: "Visual acuity screening",                      specialty: "pediatrics" },
  { code: "90460", description: "Immunization admin, first component, <18 yrs", specialty: "pediatrics" },
  { code: "90461", description: "Immunization admin, each add'l component",    specialty: "pediatrics" },
  // OB/GYN
  { code: "58300", description: "Insertion of IUD",                             specialty: "obgyn" },
  { code: "58301", description: "Removal of IUD",                               specialty: "obgyn" },
  { code: "11981", description: "Insertion, implantable contraceptive",         specialty: "obgyn" },
  { code: "11982", description: "Removal, implantable contraceptive",           specialty: "obgyn" },
  { code: "57454", description: "Colposcopy with biopsy of cervix",             specialty: "obgyn" },
  { code: "57461", description: "Colposcopy with LEEP",                         specialty: "obgyn" },
  { code: "57500", description: "Cervical biopsy, punch, single",               specialty: "obgyn" },
  { code: "76805", description: "OB ultrasound, 14+ weeks",                     specialty: "obgyn" },
  { code: "76817", description: "OB ultrasound, transvaginal",                  specialty: "obgyn" },
  { code: "59025", description: "Fetal non-stress test",                        specialty: "obgyn" },
  { code: "88142", description: "Pap smear, liquid-based preparation",          specialty: "obgyn" },
  { code: "87624", description: "HPV, high-risk types",                         specialty: "obgyn" },
  { code: "87625", description: "HPV, types 16 and 18",                         specialty: "obgyn" },
  // Psychiatry / Behavioral Health
  { code: "90791", description: "Psychiatric diagnostic evaluation",            specialty: "behavioral_health" },
  { code: "90792", description: "Psychiatric diagnostic eval with medical services (MD/NP only)", specialty: "behavioral_health" },
  { code: "90832", description: "Individual psychotherapy, 30 min",             specialty: "behavioral_health" },
  { code: "90834", description: "Individual psychotherapy, 45 min",             specialty: "behavioral_health" },
  { code: "90837", description: "Individual psychotherapy, 60 min",             specialty: "behavioral_health" },
  { code: "90833", description: "Psychotherapy add-on to E&M, 30 min",         specialty: "behavioral_health" },
  { code: "90836", description: "Psychotherapy add-on to E&M, 45 min",         specialty: "behavioral_health" },
  { code: "90838", description: "Psychotherapy add-on to E&M, 60 min",         specialty: "behavioral_health" },
  { code: "90839", description: "Psychotherapy for crisis, first 60 min",       specialty: "behavioral_health" },
  { code: "90840", description: "Psychotherapy for crisis, each add'l 30 min", specialty: "behavioral_health" },
  { code: "90846", description: "Family psychotherapy without patient",         specialty: "behavioral_health" },
  { code: "90847", description: "Family psychotherapy with patient present",    specialty: "behavioral_health" },
  { code: "90849", description: "Multiple family group psychotherapy",          specialty: "behavioral_health" },
  { code: "90853", description: "Group psychotherapy",                          specialty: "behavioral_health" },
  { code: "90785", description: "Interactive complexity add-on",                specialty: "behavioral_health" },
  { code: "90845", description: "Psychoanalysis",                               specialty: "behavioral_health" },
  // Psychology testing
  { code: "96130", description: "Psychological testing evaluation, first hour",          specialty: "behavioral_health" },
  { code: "96131", description: "Psychological testing, each add'l hour",                specialty: "behavioral_health" },
  { code: "96132", description: "Neuropsychological testing evaluation, first hour",     specialty: "behavioral_health" },
  { code: "96133", description: "Neuropsychological testing, each add'l hour",           specialty: "behavioral_health" },
  { code: "96136", description: "Psychological testing administration, first 30 min",    specialty: "behavioral_health" },
  { code: "96137", description: "Psychological testing administration, each add'l 30 min", specialty: "behavioral_health" },
  { code: "96138", description: "Tech administration of psych tests, first 30 min",     specialty: "behavioral_health" },
  { code: "96139", description: "Tech administration of psych tests, each add'l 30 min", specialty: "behavioral_health" },
  // Physical Therapy
  { code: "97161", description: "PT evaluation, low complexity",                specialty: "physical_therapy" },
  { code: "97162", description: "PT evaluation, moderate complexity",           specialty: "physical_therapy" },
  { code: "97163", description: "PT evaluation, high complexity",               specialty: "physical_therapy" },
  { code: "97164", description: "PT re-evaluation",                             specialty: "physical_therapy" },
  { code: "97010", description: "Hot/cold packs (unattended)",                  specialty: "physical_therapy" },
  { code: "97012", description: "Mechanical traction",                          specialty: "physical_therapy" },
  { code: "97014", description: "Electrical stimulation (unattended)",          specialty: "physical_therapy" },
  { code: "97032", description: "Electrical stimulation (attended)",            specialty: "physical_therapy" },
  { code: "97035", description: "Ultrasound therapy",                           specialty: "physical_therapy" },
  { code: "97110", description: "Therapeutic exercise (per 15 min)",           specialty: "physical_therapy" },
  { code: "97112", description: "Neuromuscular reeducation (per 15 min)",      specialty: "physical_therapy" },
  { code: "97116", description: "Gait training (per 15 min)",                  specialty: "physical_therapy" },
  { code: "97124", description: "Massage (per 15 min)",                        specialty: "physical_therapy" },
  { code: "97140", description: "Manual therapy (per 15 min)",                 specialty: "physical_therapy" },
  { code: "97530", description: "Therapeutic activities (per 15 min)",         specialty: "physical_therapy" },
  { code: "97535", description: "Self-care/home management training",          specialty: "physical_therapy" },
  { code: "97750", description: "Physical performance test/measurement",        specialty: "physical_therapy" },
  { code: "97760", description: "Orthotic management, upper extremity",         specialty: "physical_therapy" },
  { code: "97763", description: "Orthotic/prosthetic management, established patient", specialty: "physical_therapy" },
  // Occupational Therapy
  { code: "97165", description: "OT evaluation, low complexity",                specialty: "occupational_therapy" },
  { code: "97166", description: "OT evaluation, moderate complexity",           specialty: "occupational_therapy" },
  { code: "97167", description: "OT evaluation, high complexity",               specialty: "occupational_therapy" },
  { code: "97168", description: "OT re-evaluation",                             specialty: "occupational_therapy" },
  { code: "97129", description: "Therapeutic intervention, cognitive function, first 15 min",       specialty: "occupational_therapy" },
  { code: "97130", description: "Therapeutic intervention, cognitive function, each add'l 15 min",  specialty: "occupational_therapy" },
  { code: "97537", description: "Community/work reintegration training",        specialty: "occupational_therapy" },
  { code: "97542", description: "Wheelchair management training",               specialty: "occupational_therapy" },
  // Speech Therapy (SLP)
  { code: "92521", description: "Evaluation, speech fluency",                   specialty: "speech_language" },
  { code: "92522", description: "Evaluation, speech sound production",          specialty: "speech_language" },
  { code: "92523", description: "Evaluation, speech sound + language comprehension", specialty: "speech_language" },
  { code: "92524", description: "Behavioral analysis, voice/resonance",         specialty: "speech_language" },
  { code: "92610", description: "Evaluation of oral/pharyngeal swallowing function", specialty: "speech_language" },
  { code: "92611", description: "Modified barium swallow (motion fluoroscopy)", specialty: "speech_language" },
  { code: "92612", description: "FEES (flexible endoscopic evaluation of swallowing)", specialty: "speech_language" },
  { code: "92507", description: "Treatment, speech/language/voice, individual", specialty: "speech_language" },
  { code: "92508", description: "Treatment, speech/language, group (2+ patients)", specialty: "speech_language" },
  { code: "92526", description: "Treatment, swallowing dysfunction",            specialty: "speech_language" },
  // Chiropractic
  { code: "98940", description: "Chiropractic manipulation, spinal, 1–2 regions", specialty: "chiropractic" },
  { code: "98941", description: "Chiropractic manipulation, spinal, 3–4 regions", specialty: "chiropractic" },
  { code: "98942", description: "Chiropractic manipulation, spinal, 5 regions",   specialty: "chiropractic" },
  { code: "98943", description: "Chiropractic manipulation, extraspinal",          specialty: "chiropractic" },
  // Cardiology
  { code: "93010", description: "ECG, interpretation and report only",          specialty: "cardiology" },
  { code: "93224", description: "Holter monitor, 24 hr, with analysis/report",  specialty: "cardiology" },
  { code: "93306", description: "Echo transthoracic, real-time 2D with Doppler", specialty: "cardiology" },
  { code: "93308", description: "Echo transthoracic, follow-up or limited",     specialty: "cardiology" },
  { code: "93015", description: "Cardiovascular stress test, complete",         specialty: "cardiology" },
  { code: "93016", description: "Cardiovascular stress test, supervision only", specialty: "cardiology" },
  { code: "93018", description: "Cardiovascular stress test, interpretation only", specialty: "cardiology" },
  { code: "93350", description: "Echocardiography, stress, rest and post",      specialty: "cardiology" },
  { code: "93880", description: "Duplex carotid artery scan, bilateral",        specialty: "cardiology" },
  { code: "93970", description: "Duplex extremity venous scan, bilateral",      specialty: "cardiology" },
  { code: "93971", description: "Duplex extremity venous scan, unilateral",     specialty: "cardiology" },
  // Neurology
  { code: "95816", description: "EEG, awake and drowsy",                        specialty: "neurology" },
  { code: "95819", description: "EEG, awake and asleep",                        specialty: "neurology" },
  { code: "95827", description: "EEG, all night recording",                     specialty: "neurology" },
  { code: "95860", description: "EMG, 1 extremity",                             specialty: "neurology" },
  { code: "95861", description: "EMG, 2 extremities",                           specialty: "neurology" },
  { code: "95864", description: "EMG, 4 extremities",                           specialty: "neurology" },
  { code: "95907", description: "Nerve conduction, 1–2 studies",                specialty: "neurology" },
  { code: "95908", description: "Nerve conduction, 3–4 studies",                specialty: "neurology" },
  { code: "95910", description: "Nerve conduction, 7–8 studies",                specialty: "neurology" },
  { code: "95912", description: "Nerve conduction, 11–12 studies",              specialty: "neurology" },
  { code: "95806", description: "Home sleep apnea test (HSAT)",                 specialty: "neurology" },
  { code: "95807", description: "Polysomnography, 6+ hrs, initial staging",     specialty: "neurology" },
  { code: "95810", description: "Polysomnography, 6+ hrs",                      specialty: "neurology" },
  { code: "95930", description: "Visual evoked potential",                       specialty: "neurology" },
  // Gastroenterology
  { code: "45378", description: "Colonoscopy, diagnostic",                      specialty: "gastroenterology" },
  { code: "45380", description: "Colonoscopy with biopsy",                      specialty: "gastroenterology" },
  { code: "45385", description: "Colonoscopy with polypectomy, snare",          specialty: "gastroenterology" },
  { code: "45390", description: "Colonoscopy with endoscopic mucosal resection", specialty: "gastroenterology" },
  { code: "43239", description: "EGD with biopsy",                              specialty: "gastroenterology" },
  { code: "43245", description: "EGD with dilation",                            specialty: "gastroenterology" },
  { code: "43251", description: "EGD with removal of lesion by snare",          specialty: "gastroenterology" },
  { code: "43255", description: "EGD with control of bleeding",                 specialty: "gastroenterology" },
  { code: "G0105", description: "Colorectal cancer screening, high risk (colonoscopy)", specialty: "gastroenterology" },
  { code: "G0121", description: "Colorectal cancer screening, not high risk",   specialty: "gastroenterology" },
  // Dermatology
  { code: "11102", description: "Tangential shave biopsy, single",              specialty: "dermatology" },
  { code: "11103", description: "Tangential shave biopsy, each add'l",          specialty: "dermatology" },
  { code: "11104", description: "Punch biopsy, single",                         specialty: "dermatology" },
  { code: "11105", description: "Punch biopsy, each add'l",                     specialty: "dermatology" },
  { code: "11106", description: "Incisional biopsy, single",                    specialty: "dermatology" },
  { code: "17000", description: "Destruction, premalignant lesion, first",      specialty: "dermatology" },
  { code: "17003", description: "Destruction, premalignant lesion, each add'l (2–14)", specialty: "dermatology" },
  { code: "17004", description: "Destruction, premalignant lesions, 15+",       specialty: "dermatology" },
  { code: "17110", description: "Destruction, benign lesions, up to 14",        specialty: "dermatology" },
  { code: "17111", description: "Destruction, benign lesions, 15+",             specialty: "dermatology" },
  { code: "17260", description: "Destruction, malignant lesion, trunk/arms/legs, <0.5 cm", specialty: "dermatology" },
  { code: "17261", description: "Destruction, malignant, trunk/arms/legs, 0.6–1.0 cm",    specialty: "dermatology" },
  { code: "11200", description: "Removal of skin tags, up to 15",               specialty: "dermatology" },
  { code: "10060", description: "I&D abscess, simple",                          specialty: "dermatology" },
  { code: "10061", description: "I&D abscess, complicated",                     specialty: "dermatology" },
  { code: "96910", description: "Photochemotherapy with UVB",                   specialty: "dermatology" },
  { code: "96912", description: "Photochemotherapy with PUVA",                  specialty: "dermatology" },
  // Orthopedic Surgery
  { code: "20610", description: "Aspiration/injection, major joint (knee, shoulder, hip)", specialty: "orthopedics" },
  { code: "20611", description: "Aspiration/injection, major joint, with US guidance",     specialty: "orthopedics" },
  { code: "20605", description: "Aspiration/injection, intermediate joint",                specialty: "orthopedics" },
  { code: "20606", description: "Aspiration/injection, intermediate joint, with US guidance", specialty: "orthopedics" },
  { code: "20600", description: "Aspiration/injection, small joint (finger, toe)",         specialty: "orthopedics" },
  { code: "20604", description: "Aspiration/injection, small joint, with US guidance",     specialty: "orthopedics" },
  { code: "20550", description: "Injection, tendon sheath",                      specialty: "orthopedics" },
  { code: "20551", description: "Injection, tendon origin/insertion",            specialty: "orthopedics" },
  { code: "20560", description: "Needle insertion, trigger point, 1–2 muscles (dry needling)", specialty: "orthopedics" },
  { code: "25600", description: "Closed Tx distal radial fracture, w/o manipulation", specialty: "orthopedics" },
  { code: "25605", description: "Closed Tx distal radial fracture, with manipulation", specialty: "orthopedics" },
  { code: "29075", description: "Application, short arm cast",                  specialty: "orthopedics" },
  { code: "29085", description: "Application, long arm cast",                   specialty: "orthopedics" },
  { code: "29105", description: "Application, long arm splint",                 specialty: "orthopedics" },
  { code: "29125", description: "Application, short arm splint, static",        specialty: "orthopedics" },
  { code: "29505", description: "Application, long leg splint",                 specialty: "orthopedics" },
  { code: "29515", description: "Application, short leg splint",                specialty: "orthopedics" },
  { code: "29530", description: "Strapping, knee",                              specialty: "orthopedics" },
  { code: "29540", description: "Strapping, ankle and/or foot",                 specialty: "orthopedics" },
  // Podiatry
  { code: "11720", description: "Debridement nail(s), up to 5",                 specialty: "podiatry" },
  { code: "11721", description: "Debridement nail(s), 6+",                      specialty: "podiatry" },
  { code: "11730", description: "Avulsion nail plate, single",                   specialty: "podiatry" },
  { code: "11732", description: "Avulsion nail plate, each add'l",               specialty: "podiatry" },
  { code: "11740", description: "Evacuation subungual hematoma",                 specialty: "podiatry" },
  { code: "11750", description: "Excision nail and matrix",                      specialty: "podiatry" },
  { code: "11765", description: "Wedge excision skin/nail fold",                 specialty: "podiatry" },
  { code: "11055", description: "Paring/cutting benign hyperkeratotic lesion, single", specialty: "podiatry" },
  { code: "11056", description: "Paring/cutting, 2–4 lesions",                   specialty: "podiatry" },
  { code: "11057", description: "Paring/cutting, 4+ lesions",                    specialty: "podiatry" },
  { code: "97597", description: "Debridement, open wound, first 20 sq cm",      specialty: "podiatry" },
  { code: "97598", description: "Debridement, open wound, each add'l 20 sq cm", specialty: "podiatry" },
  { code: "64455", description: "Injection, plantar fascia",                     specialty: "podiatry" },
  { code: "28001", description: "I&D bursa, foot",                               specialty: "podiatry" },
  { code: "28292", description: "Bunionectomy, simple",                          specialty: "podiatry" },
  { code: "28296", description: "Bunionectomy with metatarsal osteotomy",        specialty: "podiatry" },
  { code: "29550", description: "Strapping, toes",                               specialty: "podiatry" },
  // Optometry
  { code: "92004", description: "Comprehensive ophthalmologic examination, new patient",         specialty: "optometry" },
  { code: "92012", description: "Ophthalmologic examination, established patient, intermediate", specialty: "optometry" },
  { code: "92014", description: "Ophthalmologic examination, established patient, comprehensive", specialty: "optometry" },
  { code: "92015", description: "Refraction (verify payer coverage — often excluded)",          specialty: "optometry" },
  { code: "92025", description: "Corneal topography",                            specialty: "optometry" },
  { code: "92081", description: "Visual field examination, limited, unilateral", specialty: "optometry" },
  { code: "92082", description: "Visual field examination, intermediate, bilateral", specialty: "optometry" },
  { code: "92083", description: "Visual field examination, extended, bilateral", specialty: "optometry" },
  { code: "92100", description: "Serial tonometry",                              specialty: "optometry" },
  { code: "92134", description: "Retinal nerve fiber analysis (OCT)",            specialty: "optometry" },
  { code: "92135", description: "Scanning computerized ophthalmic diagnostic imaging", specialty: "optometry" },
  { code: "92228", description: "Remote imaging for retinal disease monitoring", specialty: "optometry" },
  { code: "92250", description: "Fundus photography",                            specialty: "optometry" },
  // Allergy & Immunology
  { code: "95004", description: "Percutaneous allergy tests, immediate type reaction", specialty: "allergy" },
  { code: "95017", description: "Allergy tests, venom, stinging insect",        specialty: "allergy" },
  { code: "95024", description: "Intracutaneous allergy tests, immediate type", specialty: "allergy" },
  { code: "95044", description: "Patch tests",                                   specialty: "allergy" },
  { code: "95070", description: "Bronchial challenge test with histamine/methacholine", specialty: "allergy" },
  { code: "95115", description: "Injection, allergy immunotherapy, single",     specialty: "allergy" },
  { code: "95117", description: "Injection, allergy immunotherapy, 2+ injections", specialty: "allergy" },
  { code: "95144", description: "Allergen immunotherapy, prepare and provide",  specialty: "allergy" },
  { code: "95165", description: "Allergen immunotherapy, professional services, 1–8 doses", specialty: "allergy" },
  // Endocrinology
  { code: "95250", description: "Ambulatory continuous glucose monitoring (CGM), professional", specialty: "endocrinology" },
  { code: "95251", description: "CGM, interpretation and report",                specialty: "endocrinology" },
  { code: "77080", description: "Bone density study (DXA), axial",              specialty: "endocrinology" },
  { code: "77081", description: "Bone density study, appendicular",             specialty: "endocrinology" },
  { code: "76536", description: "US, soft tissue neck/thyroid",                  specialty: "endocrinology" },
  // Rheumatology
  { code: "96365", description: "IV infusion, therapeutic, first hour (biologics)", specialty: "rheumatology" },
  { code: "96366", description: "IV infusion, each add'l hour",                 specialty: "rheumatology" },
  { code: "96401", description: "Chemotherapy injection, non-hormonal, sub-Q/IM", specialty: "rheumatology" },
  { code: "77002", description: "Fluoroscopic guidance for needle placement",   specialty: "rheumatology" },
  // Urology
  { code: "52000", description: "Cystourethroscopy",                             specialty: "urology" },
  { code: "52204", description: "Cystourethroscopy with biopsy",                 specialty: "urology" },
  { code: "52005", description: "Cystourethroscopy with ureteral catheterization", specialty: "urology" },
  { code: "55700", description: "Prostate biopsy, needle",                      specialty: "urology" },
  { code: "55706", description: "Prostate biopsy, transperineal saturation",    specialty: "urology" },
  { code: "76872", description: "US, transrectal (TRUS)",                        specialty: "urology" },
  { code: "51701", description: "Insertion of non-indwelling bladder catheter", specialty: "urology" },
  { code: "51702", description: "Insertion of temporary indwelling bladder catheter", specialty: "urology" },
]

// Common ICD-10 codes across all 25 outpatient specialties on Claima
export const COMMON_ICD10_CODES = [
  // Primary care / internal medicine / family medicine
  { code: "I10", description: "Essential hypertension" },
  { code: "E11.9", description: "Type 2 diabetes mellitus without complications" },
  { code: "E11.65", description: "Type 2 diabetes with hyperglycemia" },
  { code: "E78.5", description: "Hyperlipidemia, unspecified" },
  { code: "Z00.00", description: "Encounter for general adult medical examination" },
  { code: "J06.9", description: "Acute upper respiratory infection, unspecified" },
  { code: "Z23", description: "Encounter for immunization" },
  { code: "F17.210", description: "Nicotine dependence, cigarettes, uncomplicated" },
  // Pediatrics
  { code: "Z00.129", description: "Encounter for routine child health examination" },
  { code: "Z13.88", description: "Encounter for screening for developmental disorder" },
  { code: "F84.0", description: "Autism spectrum disorder" },
  { code: "J45.20", description: "Mild intermittent asthma, uncomplicated" },
  { code: "L20.9", description: "Atopic dermatitis, unspecified" },
  // OB/GYN
  { code: "Z34.00", description: "Encounter for supervision of normal pregnancy, unspecified trimester" },
  { code: "N93.9", description: "Abnormal uterine and vaginal bleeding, unspecified" },
  { code: "N89.3", description: "Dysplasia of cervix uteri, unspecified" },
  { code: "Z30.09", description: "Encounter for other general counseling on contraception" },
  // Behavioral health — depression / anxiety / trauma
  { code: "F32.0", description: "Major depressive disorder, single episode, mild" },
  { code: "F32.1", description: "Major depressive disorder, single episode, moderate" },
  { code: "F32.2", description: "Major depressive disorder, single episode, severe" },
  { code: "F33.1", description: "Major depressive disorder, recurrent, moderate" },
  { code: "F41.1", description: "Generalized anxiety disorder" },
  { code: "F41.0", description: "Panic disorder" },
  { code: "F40.10", description: "Social anxiety disorder, unspecified" },
  { code: "F43.10", description: "PTSD, unspecified" },
  { code: "F43.12", description: "PTSD, chronic" },
  { code: "F43.20", description: "Adjustment disorder, unspecified" },
  // Behavioral health — other
  { code: "F90.0", description: "ADHD, predominantly inattentive" },
  { code: "F90.2", description: "ADHD, combined type" },
  { code: "F31.1", description: "Bipolar I disorder, current manic episode, without psychosis" },
  { code: "F31.81", description: "Bipolar II disorder" },
  { code: "F20.9", description: "Schizophrenia, unspecified" },
  { code: "F60.3", description: "Borderline personality disorder" },
  { code: "F50.00", description: "Anorexia nervosa, unspecified" },
  { code: "F10.20", description: "Alcohol use disorder, moderate" },
  // Musculoskeletal / PT / orthopedics
  { code: "M54.50", description: "Low back pain, unspecified" },
  { code: "M54.2", description: "Cervicalgia (neck pain)" },
  { code: "M25.511", description: "Pain in right shoulder" },
  { code: "M25.512", description: "Pain in left shoulder" },
  { code: "M25.561", description: "Pain in right knee" },
  { code: "M25.562", description: "Pain in left knee" },
  { code: "M17.11", description: "Primary osteoarthritis, right knee" },
  { code: "M19.011", description: "Primary osteoarthritis, right shoulder" },
  { code: "S52.501A", description: "Unspecified fracture of lower end of right radius, initial encounter" },
  // Cardiology
  { code: "I25.10", description: "Atherosclerotic heart disease of native coronary artery" },
  { code: "I50.9", description: "Heart failure, unspecified" },
  { code: "I48.0", description: "Paroxysmal atrial fibrillation" },
  { code: "I35.0", description: "Nonrheumatic aortic (valve) stenosis" },
  { code: "Z82.49", description: "Family history of ischemic heart disease" },
  // Neurology
  { code: "G35", description: "Multiple sclerosis" },
  { code: "G20", description: "Parkinson's disease" },
  { code: "G40.909", description: "Epilepsy, unspecified, not intractable, without status epilepticus" },
  { code: "G43.909", description: "Migraine, unspecified, not intractable, without status migrainosus" },
  { code: "G62.9", description: "Polyneuropathy, unspecified" },
  { code: "G47.33", description: "Obstructive sleep apnea" },
  { code: "G89.29", description: "Other chronic pain" },
  // Gastroenterology
  { code: "K21.0", description: "GERD with esophagitis" },
  { code: "K57.30", description: "Diverticulosis of large intestine without perforation or abscess" },
  { code: "Z12.11", description: "Encounter for screening for malignant neoplasm of colon" },
  { code: "K50.90", description: "Crohn's disease of small intestine, unspecified, without complications" },
  { code: "K51.90", description: "Ulcerative colitis, unspecified, without complications" },
  // Dermatology
  { code: "L70.0", description: "Acne vulgaris" },
  { code: "L40.0", description: "Psoriasis vulgaris" },
  { code: "C43.9", description: "Malignant melanoma of skin, unspecified" },
  { code: "L57.0", description: "Actinic keratosis" },
  { code: "B00.1", description: "Herpesviral vesicular dermatitis" },
  // Podiatry
  { code: "M79.671", description: "Pain in right foot" },
  { code: "L60.0", description: "Ingrowing nail" },
  { code: "B35.3", description: "Tinea pedis" },
  { code: "M72.2", description: "Plantar fibromatosis" },
  { code: "L84", description: "Corns and callosities" },
  { code: "E11.621", description: "Type 2 diabetes with foot ulcer" },
  // Optometry
  { code: "H52.4", description: "Presbyopia" },
  { code: "H25.11", description: "Age-related nuclear cataract, right eye" },
  { code: "H35.30", description: "Unspecified macular degeneration" },
  { code: "H40.11X0", description: "Primary open-angle glaucoma, right eye, stage unspecified" },
  { code: "H10.9", description: "Unspecified conjunctivitis" },
  { code: "H53.001", description: "Unspecified amblyopia, right eye" },
  { code: "H52.10", description: "Myopia, unspecified" },
  // Allergy
  { code: "J30.9", description: "Allergic rhinitis, unspecified" },
  { code: "L50.0", description: "Allergic urticaria" },
  { code: "T78.1XXA", description: "Other adverse food reactions, not elsewhere classified, initial encounter" },
  // Endocrinology
  { code: "E03.9", description: "Hypothyroidism, unspecified" },
  { code: "E05.90", description: "Hyperthyroidism, unspecified, without thyrotoxic crisis" },
  { code: "E66.01", description: "Morbid (severe) obesity due to excess calories" },
  { code: "M81.0", description: "Age-related osteoporosis without current pathological fracture" },
  // Rheumatology
  { code: "M06.9", description: "Rheumatoid arthritis, unspecified" },
  { code: "M32.9", description: "Systemic lupus erythematosus, unspecified" },
  { code: "M35.00", description: "Sjögren syndrome, unspecified" },
  { code: "M45.9", description: "Ankylosing spondylitis of unspecified sites in spine" },
  { code: "M10.9", description: "Gout, unspecified" },
  // Urology
  { code: "N40.0", description: "Benign prostatic hyperplasia without lower urinary tract symptoms" },
  { code: "N39.0", description: "Urinary tract infection, site not specified" },
  { code: "N20.0", description: "Calculus of kidney" },
  { code: "C67.9", description: "Malignant neoplasm of bladder, unspecified" },
  { code: "R33.9", description: "Retention of urine, unspecified" },
  // Chiropractic
  { code: "M99.01", description: "Segmental and somatic dysfunction of cervical region" },
  { code: "M99.03", description: "Segmental and somatic dysfunction of lumbar region" },
  { code: "S13.4XXA", description: "Sprain of ligaments of cervical spine, initial encounter (whiplash)" },
  // Preventive / screening
  { code: "Z03.89", description: "Encounter for observation for other suspected diseases ruled out" },
  { code: "Z13.89", description: "Encounter for screening for other disorder" },
]
