import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import SessionTimeout from "@/components/SessionTimeout"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const SITE_URL = "https://claima.io"
const TITLE = "Claima — AI Medical Billing"
const DESCRIPTION =
  "AI-native medical billing for outpatient practices. Claim submission, denial appeals, ERA posting, and patient statements — no billing department required."

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: TITLE,
    template: "%s · Claima",
  },
  description: DESCRIPTION,
  applicationName: "Claima",
  keywords: [
    "medical billing", "revenue cycle management", "RCM", "denial management",
    "837P", "ERA posting", "eligibility verification", "outpatient practice",
    "AI medical billing", "HIPAA",
  ],
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: "Claima",
    title: TITLE,
    description: DESCRIPTION,
    // og-image is generated by src/app/opengraph-image — Next injects it here.
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-gray-50">
        <SessionTimeout />
        {children}
      </body>
    </html>
  )
}
